registration_platform/auth_app/urls.py
from django.contrib.auth.views import (LogoutView,
                                       PasswordResetView, PasswordResetDoneView,
                                       PasswordResetConfirmView, PasswordResetCompleteView,
                                       PasswordChangeView, PasswordChangeDoneView)
from django.urls import path
from .views import *

urlpatterns = [
    # Controllers for users management
    path('login/', UserLoginView.as_view(), name='login'),
    path('register/', UserRegisterView.as_view(), name='register'),
    path('logout/', LogoutView.as_view(next_page='login'), name='logout'),
    # Controllers for change password
    path('password_change/', PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', PasswordChangeDoneView.as_view(), name='password_change_done'),
    # Controllers for reset password
    path('password-reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

registration_platform/registration_platform/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('auth_app.urls')),
    path('exams/', include('enrollment.urls')),
    path('verification/', include('verification.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # urlpatterns.extend(
    #     [static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
    #      static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)]
    # )

registration_platform/verification/models.py
import os
from enum import Enum

from channels.db import database_sync_to_async
from django.conf import settings
from django.core.validators import FileExtensionValidator
from django.db import models

from .utilities import build_document_path, build_document_text_path


class DocumentName(Enum):
    SNILS = 'СНИЛС'
    PASSPORT = 'Паспорт'
    NAME_CHANGE = 'Документ о перемене имени'
    MARRIAGE_OR_DIVORCE = 'Документ о заключении или расторжении брака'
    OTHER_DOCUMENT_1 = 'Иной документ 1'
    BACHELORS_DIPLOMA = 'Диплом бакалавра'
    MASTERS_DIPLOMA = 'Диплом магистра'
    EMPLOYMENT_HISTORY = 'Трудовая книжка'
    ADVANCED_TRAINING_CERTIFICATE = 'Сертификат о повышении квалификации'
    OTHER_DOCUMENT_2 = 'Иной документ 2'
    NRS = 'НРС'
    DATA_PROCESSING_AGREEMENT = 'Согласие на обработку данных'

    @property
    def name(self):
        return self._name_.lower()

    @classmethod
    def choices(cls):
        return [(document_type.name, document_type.value) for document_type in cls]

    @classmethod
    def get_names(cls):
        return [document_type.name for document_type in cls]


class DocumentStatus(Enum):
    NOT_UPLOADED = 'Не загружен'
    IN_PROGRESS = 'В обработке'
    VERIFICATION_FAILED = 'Проверка не пройдена'
    APPROVED = 'Одобрен'

    @property
    def name(self):
        return self._name_.lower()

    @classmethod
    def choices(cls):
        return [(status.name, status.value) for status in cls]


class UserDocument(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='documents')
    document_name = models.CharField(max_length=100, choices=DocumentName.choices(), verbose_name="Тип документа")
    status = models.CharField(max_length=20, default='not_uploaded', choices=DocumentStatus.choices(),
                              verbose_name="Статус")
    uploaded_file = models.FileField(upload_to=build_document_path, validators=[
        FileExtensionValidator(allowed_extensions=['pdf'], message='Выберите файл в формате PDF')
    ], verbose_name="Файл", blank=True, default='')
    extracted_text_file = models.FileField(upload_to=build_document_text_path, verbose_name='Извлеченный текст',
                                           default='', blank=True)

    class Meta:
        verbose_name = 'Документ'
        verbose_name_plural = 'Документы'

    def save(self, *args, **kwargs):
        # Check does uploaded_file already exist
        if self.pk:
            old_document = UserDocument.objects.get(pk=self.pk)
            old_file_path = None
            print(f'From save')
            print(f'{old_document.extracted_text_file=}')
            print(f'{self.extracted_text_file=}')
            if old_document.extracted_text_file and old_document.extracted_text_file != self.extracted_text_file:
                self.remove_old_file(old_document.extracted_text_file.path)

            if old_document.uploaded_file and old_document.uploaded_file != self.uploaded_file:
                self.remove_old_file(old_document.uploaded_file.path)

        super(UserDocument, self).save(*args, **kwargs)

    @staticmethod
    def remove_old_file(old_file_path):
        if old_file_path:
            print(f'{old_file_path=}')
            if os.path.isfile(old_file_path):
                os.remove(old_file_path)

    def update_status(self, status: str) -> None:
        self.status = status
        self.save(update_fields=('status',))

    def update_file(self, file) -> None:
        self.uploaded_file = file
        self.save(update_fields=('uploaded_file',))

    @classmethod
    def update_status_by_id(cls, document_id: int, status: str):
        document = cls.objects.get(id=document_id)
        document.update_status(status)
        return document

    @classmethod
    @database_sync_to_async
    def async_get_status_by_id(cls, document_id: int) -> status:
        document = cls.objects.get(id=document_id)
        return document.status

    @classmethod
    def update_document_file_by_id(cls, document_id: int, file):
        document = cls.objects.get(id=document_id)
        document.update_file(file)
        return document

    def get_filename(self):
        return os.path.basename(self.uploaded_file.name)

registration_platform/templates/account.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="content">
        <div class="account_container">
            <div class="user_profile">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ user_profile_form.as_p }}
                    <button type="submit">Сохранить</button>
                </form>
            </div>
            <div class="user_documents">
                {% for user_document in user_documents %}
                    <form id="uploadDocumentForm-{{ user_document.id }}" method="post" enctype="multipart/form-data">
                        <p>
                            {{ user_document.get_document_name_display }}
                        </p>
                        <p>
                            Статус:
                            <span id="status-{{ user_document.id }}">&nbsp;
                                {{ user_document.get_status_display }}
                            </span>
                        </p>
                        {% if user_document.uploaded_file %}
                            <p>
                                <span style="font-size: smaller">Загружен файл: {{ user_document.get_filename }}</span>
                            </p>
                        {% endif %}
                        <p>
                            <span style="font-size: smaller">
                                Загрузить новый файл в формате PDF
                            </span>
                            <input  class="file-upload"
                                    type="file"
                                    id="document-{{ user_document.id }}"
                                    name="{{ user_document.document_name }}"
                                    accept="application/pdf"
                                    required>
                        </p>
                    </form>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

{% block extra_js %}
    <script>
        window.CSRF_TOKEN = '{{ csrf_token }}';
    </script>
    <script defer src="{% static 'account.js' %}"></script>
{% endblock %}


registration_platform/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Sosha Zhuk. - {% block title %}Регистрация на экзамены{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <script defer src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"
            integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2"
            crossorigin="anonymous">
    </script>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <script defer src="{% static 'global.js' %}"></script>
</head>
<body>
    <header>
        <nav class="header_container">
            <div class="logo_container">
                <a class="logo" href="{% url 'index' %}">
                    <img src="{% static 'logo.png' %}" alt="site logo" title="Лого сайта">
                </a>
                <div class="describer">
                    <div class="title">
                        <h2 translate="no">Registration</h2>
                    </div>
                    <div class="role">
                        Регистрация на экзамены
                    </div>
                </div>
            </div>
            <div class="auth_container">
                {% if user.is_authenticated %}
                    <div class="profile">
                        <div>
                            <a href="#">{{ user.last_name }} {{ user.first_name }}</a>
                        </div>
                        <div class="submenu_profile" style="display: none;">
                            <div>
                                <p>
                                    <a style="color:rgba(138,33,173,0.69)"
                                       class="fa fa-tasks"
                                       href="#">
                                        Ваши экзамены
                                    </a>
                                </p>
                                <p>
                                    <a style="color:rgba(33,73,173,0.69)"
                                       href="#">
                                        Настройки
                                    </a>
                                </p>
                                <p>
                                    <a style="color:rgba(33,73,173,0.69)"
                                       href="#">
                                        Изменить пароль
                                    </a>
                                </p>
                                <p class="fa fa-sign-out">
                                    <a style="color: rgba(238, 68, 68, 0.93)" href="{% url 'logout' %}">Выход</a>
                                </p>
                            </div>
                        </div>
                    </div>
                    {% if user.is_staff %}
                        <div>
                            <a href="#">Создать новый экзамен</a>
                        </div>
                    {% endif %}
                {% else %}
                    <div class="nav-toggle"><span></span></div>
                    <div class="login">
                        <a href="{% url 'login' %}" style="color: #000">Вход</a>
                    </div>
                    <div class="register">
                        <a href="{% url 'register' %}" style="color: #fff">Регистрация</a>
                    </div>
                {% endif %}
            </div>
        </nav>
    </header>
    <main>
        {% block content %}{% endblock %}
        {% block extra_js %}{% endblock %}
    </main>
    <footer>
        <div class="footer_container">
            <div class="logo">
                <div class="copyright-mark">
                    <p>
                        <img src="{% static 'logo.png' %}" alt="site logo" title="Лого сайта">
                        <span class="title">Sosha Zhuk.</span> - Регистрация на экзамены
                    </p>
                    <div>
                        &copy; {{ current_year }} Все права защищены
                    </div>
                </div>
            </div>
            <div class="privacy">
                <a href="#">Политика конфидециальности</a>
            </div>
            <div class="terms">
                <a href="#">Условия использования</a>
            </div>
        </div>
    </footer>
</body>
</html>

registration_platform/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% endblock %}

registration_platform/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="main_container">
        <div class="main_item">
            <form id="form_login" method="post">
                <h3>{% block form_name %}Вход{% endblock %}</h3>
                {% csrf_token %}
                {{ form.as_p }}
                <p><a href="{% url 'password_reset' %}">Забыли пароль?</a></p>
                <p><button type="submit">Войти</button></p>
            </form>
        </div>
    </div>
{% endblock %}

registration_platform/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="main_container">
        <div class="main_item">
            <form id="form_register" method="post" enctype="multipart/form-data">
                <h3>{% block form_name %}Регистрация{% endblock %}</h3>
                {% csrf_token %}
                {{ form.as_p }}
                <p><button type="submit">Зарегистрироваться</button></p>
            </form>
        </div>
    </div>
{% endblock %}